#!/bin/sh

export PATH=/bin:/libs:/conf

error() {
    echo "INIT ERROR: $1"
    /bin/sh
}

mount -t proc proc /proc || error "Failed to mount /proc"
mount -t sysfs sysfs /sys || error "Failed to mount /sys"
mount -t tmpfs tmpfs /temp || error "Failed to mount /temp"
mount -t devtmpfs devtmpfs /dev || error "Failed to mount /dev"

dmesg > /logs/dmesg.log 2>/dev/null

clear
[ -f /conf/motd ] && cat /conf/motd || echo "Welcome to OpenCalcOS!"
exec /bin/sh
