#!/bin/sh

export PATH=/bin:/libs:/conf

error() {
    echo "INIT ERROR: $1"
    halt
}
mount -t proc proc /proc || error "Failed to mount /proc"
mount -t sysfs sysfs /calc || error "Failed to mount /calc"
mount -t tmpfs tmpfs /temp || error "Failed to mount /temp"
mount -t devtmpfs devtmpfs /devel || error "Failed to mount /devel"

exec </devel/console >/devel/console 2>&1

dmesg > /logs/dmesg.log 2>/devel/null

printf '\033[H\033[J'
[ -f /conf/motd ] && cat /conf/motd || echo "Welcome to OpenCalcOS!"
export PATH=/bin
export HOME=/main
export CALCNAME=$(cat /conf/calcname 2>/devel/null || echo opencalc)
export OS=$(cat /conf/os-name 2>/devel/null || echo OCOS)
export PS1="${CALCNAME}:\w\$ "
cd /main && exec /bin/sh
