#!/bin/sh

export PATH=/bin:/libs:/conf

error() {
    echo "INIT ERROR: $1"
    /bin/sh
}

mount -t proc proc /proc || error "Failed to mount /proc"
mount -t sysfs sysfs /calc || error "Failed to mount /calc"
mount -t tmpfs tmpfs /temp || error "Failed to mount /temp"
mount -t devtmpfs devtmpfs /devel || error "Failed to mount /devel"

dmesg > /logs/dmesg.log 2>/dev/null

clear
[ -f /conf/motd ] && cat /conf/motd || echo "Welcome to OpenCalcOS!"
export PATH=/bin
export HOME=/main
export CALCNAME=$(cat /conf/calcname 2>/dev/null || echo opencalc)
export PS1="${CALCNAME}> "
exec /bin/sh
cd /main
