#!/bin/sh

# Emit a msg to let user know this place was reached
echo "Copying to /calc"
# Had a case where cp SEGVs, let's have diagnostics for it
cp -a /mnt /calc || { echo "cp: $?"; exit 1; }
cd /calc/mnt || { echo "cd: $?"; exit 1; }
exec ./build
echo "Failed to exec ./build"
